version: "3.9"

services:
  notifications:
    build: Notifications/
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: "service_healthy"
  users:
    build: Users/
    environment:
      - ENV=prod
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_started"
      rabbitmq:
        condition: "service_healthy"
      redis:
        condition: "service_started"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
       - .env
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"


volumes:
  postgres_db:
  redis_data: