apiVersion: v1
kind: Service
metadata:
  labels:
    service: notifications
  name: notifications
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: notifications
status:
  loadBalancer: {}
