"""empty message

Revision ID: 03f45e1b7181
Revises: 2d3e8ec2be89
Create Date: 2022-09-29 15:13:04.004551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f45e1b7181'
down_revision = '2d3e8ec2be89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistedtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklistedtoken_id'), 'blacklistedtoken', ['id'], unique=False)
    op.create_index(op.f('ix_blacklistedtoken_jti'), 'blacklistedtoken', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklistedtoken_jti'), table_name='blacklistedtoken')
    op.drop_index(op.f('ix_blacklistedtoken_id'), table_name='blacklistedtoken')
    op.drop_table('blacklistedtoken')
    # ### end Alembic commands ###
