"""empty message

Revision ID: 46bede01eb2e
Revises: bb40aa263fce
Create Date: 2022-10-04 09:54:16.446580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bede01eb2e'
down_revision = 'bb40aa263fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklistedtoken', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('token', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'created_at')
    op.drop_column('blacklistedtoken', 'created_at')
    # ### end Alembic commands ###
