"""empty message

Revision ID: bb40aa263fce
Revises: acaa2f0f1c25
Create Date: 2022-10-03 23:23:31.667803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb40aa263fce'
down_revision = 'acaa2f0f1c25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklistedtoken', ['token_id'])
    op.add_column('token', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'user_id')
    op.drop_constraint(None, 'blacklistedtoken', type_='unique')
    # ### end Alembic commands ###
