# Generated by Django 4.1.2 on 2022-10-08 14:58

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hotel name')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hotel description')),
                ('address', models.CharField(max_length=100, verbose_name='Hotel address')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Hotel rating')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Hotel has parking')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Hotel has wi-fi')),
                ('owner', models.PositiveIntegerField(verbose_name='Hotel owner')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='cities.city', verbose_name='Hotel city')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.ImageField(upload_to=functools.partial(common.utils.path_and_rename, *(), **{'path': 'hotels'}), verbose_name='Image key')),
                ('hotel', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Hotel')),
            ],
        ),
    ]
