# Generated by Django 4.1.1 on 2022-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hotel name')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hotel description')),
                ('address', models.CharField(max_length=100, verbose_name='Hotel address')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Hotel rating')),
                ('has_parking', models.BooleanField(verbose_name='Hotel has parking')),
                ('owner', models.PositiveIntegerField(verbose_name='Hotel owner')),
            ],
        ),
    ]
