# Generated by Django 4.1.2 on 2022-10-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_city_alter_hotelimage_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='hotels.hotel')),
            ],
        ),
    ]
