# Generated by Django 4.1.1 on 2022-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelimage_hotel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelimage'),
        ),
    ]
