# Generated by Django 4.1.1 on 2022-09-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('hotels', '0003_alter_hotel_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='images.image'),
        ),
    ]
