# Generated by Django 4.1.2 on 2022-10-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_hotelviews_hotelview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelview',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='hotels.hotel', unique=True),
        ),
    ]
