# Generated by Django 4.1.1 on 2022-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_delete_hotelimage_alter_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Hotel has wi-fi'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Hotel has parking'),
        ),
    ]
