# Generated by Django 4.1.1 on 2022-10-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('hotels', '0005_hotel_has_wifi_alter_hotel_has_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='cities.city', verbose_name='Hotel city'),
        ),
    ]
