# Generated by Django 4.1.2 on 2022-10-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotelview_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelview',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='hotels.hotel'),
        ),
    ]
