# Generated by Django 4.1.1 on 2022-10-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
    ]
