# Generated by Django 4.1.2 on 2022-10-13 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotelview_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
