# Generated by Django 4.1.2 on 2022-10-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_hotelview_hotel_alter_hotelview_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Hotel rating'),
        ),
    ]
