# Generated by Django 4.1.3 on 2022-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Hotel description'),
        ),
    ]
