# Generated by Django 4.1.3 on 2022-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=53.905741, max_digits=9, verbose_name='Hotel latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=27.554467, max_digits=9, verbose_name='Hotel longitude'),
            preserve_default=False,
        ),
    ]
