# Generated by Django 4.1.3 on 2022-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelview',
            name='viewer',
            field=models.PositiveIntegerField(),
        ),
    ]
