# Generated by Django 4.1.3 on 2022-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_alter_hotelview_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Hotel description'),
        ),
    ]
