search_request_params = (
    "name",
    "address",
    "has_parking",
    "has_wifi",
    "has_washing_machine",
    "has_kitchen",
    "price_min",
    "price_max",
    "beds_number",
    "owner",
    "city",
    "order",
    "booking_start_date",
    "booking_end_date",
    "created_at",
    "user",
)
