apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres-db
  name: postgres-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
