# Generated by Django 4.1.1 on 2022-09-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Room name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Room description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Room price')),
                ('beds_number', models.PositiveIntegerField(verbose_name='Room beds number')),
                ('equipment_state', models.PositiveIntegerField(choices=[('0', 'Pending Verification'), ('1', 'Verified'), ('2', 'Pending Equipment'), ('3', 'Equipment Installed')], default='0', verbose_name='Room equipment state')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Hotel rooms')),
            ],
        ),
    ]
