# Generated by Django 4.1.2 on 2022-10-08 14:58

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Room name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Room description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Room price')),
                ('beds_number', models.PositiveIntegerField(verbose_name='Room beds number')),
                ('equipment_state', models.PositiveIntegerField(choices=[(0, 'Pending Verification'), (1, 'Verified'), (2, 'Pending Equipment'), (3, 'Equipment Installed')], default=0, verbose_name='Room equipment state')),
                ('has_washing_machine', models.BooleanField(default=False, verbose_name='Room has washing machine')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='Room has kitchen')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Hotel rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.ImageField(upload_to=functools.partial(common.utils.path_and_rename, *(), **{'path': 'rooms'}), verbose_name='Image key')),
                ('room', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Room image')),
            ],
        ),
    ]
