# Generated by Django 4.1.1 on 2022-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(max_length=200, verbose_name='Room image key')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(related_name='rooms', to='rooms.roomimage'),
        ),
    ]
