# Generated by Django 4.1.3 on 2022-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rooms_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Rooms number'),
            preserve_default=False,
        ),
    ]
