# Generated by Django 4.1.1 on 2022-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomimage_room_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.roomimage'),
        ),
    ]
