# Generated by Django 4.1.1 on 2022-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_delete_roomimage_alter_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Room has kitchen'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_washing_machine',
            field=models.BooleanField(default=False, verbose_name='Room has washing machine'),
        ),
    ]
