# Generated by Django 4.1.1 on 2022-10-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_has_kitchen_room_has_washing_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipment_state',
            field=models.PositiveIntegerField(choices=[(0, 'Pending Verification'), (1, 'Verified'), (2, 'Pending Equipment'), (3, 'Equipment Installed')], default=0, verbose_name='Room equipment state'),
        ),
    ]
