# Generated by Django 4.1.1 on 2022-10-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_equipment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
    ]
