"""empty message

Revision ID: f3a656b6e99b
Revises: 64b82da62908
Create Date: 2022-10-20 00:33:07.359336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3a656b6e99b'
down_revision = '64b82da62908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookingpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('payment_intent_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookingpayment_id'), 'bookingpayment', ['id'], unique=False)
    op.create_index(op.f('ix_bookingpayment_payment_intent_id'), 'bookingpayment', ['payment_intent_id'], unique=False)
    op.drop_index('ix_booking_id', table_name='booking')
    op.drop_index('ix_booking_payment_intent_id', table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('succeeded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='booking_pkey')
    )
    op.create_index('ix_booking_payment_intent_id', 'booking', ['payment_intent_id'], unique=False)
    op.create_index('ix_booking_id', 'booking', ['id'], unique=False)
    op.drop_index(op.f('ix_bookingpayment_payment_intent_id'), table_name='bookingpayment')
    op.drop_index(op.f('ix_bookingpayment_id'), table_name='bookingpayment')
    op.drop_table('bookingpayment')
    # ### end Alembic commands ###
