version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS= -Xms2048m -Xmx2048m
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.3
    container_name: logstash
    volumes:
      - ../logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elastic
      - kafka
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch
      - kafka

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka_management
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    networks:
      - kafka
      - kafka_management
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    container_name: kafka_manager
    networks:
      - kafka_management
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka


volumes:
  elasticsearch_data:


networks:
  elastic:
    driver: bridge
  kafka:
    driver: bridge
    name: shared-kafka
  kafka_management:
    driver: bridge
