version: "3.9"

services:
  notifications:
    build: ../Notifications/
    container_name: notifications
    env_file:
      - ../Notifications/.env
    volumes:
      - "../Notifications/app:/app"
    networks:
      - notifications
      - web
      - rabbitmq
      - centrifugo
    depends_on:
      rabbitmq:
        condition: "service_healthy"
      centrifugo:
        condition: "service_started"


networks:
  web:
    external: true
    name: shared-web
  rabbitmq:
    external: true
    name: shared-rabbitmq
  centrifugo:
    external: true
    name: shared-centrifugo
  notifications:
    driver: bridge
