version: "3.9"

services:
  search:
    build: ../Search
    container_name: search
    env_file:
      - ../Search/.env
    networks:
      - search
      - web
      - rabbitmq
    expose:
      - "3000"
    volumes:
      - "../Search:/search"
    depends_on:
      search_db:
        condition: "service_started"
      search_requests_db:
        condition: "service_started"
  search_db:
    image: postgres:12.0-alpine
    container_name: search_db
    volumes:
      - search_db_data:/var/lib/postgresql/data/
    env_file:
      - ../Search/.env
    networks:
      - search
    expose:
      - "5432"
  search_requests_db:
    image: mongo:6.0.2
    container_name: search_requests_db
    volumes:
      - search_requests_db_data:/var/lib/mongodb/data/
    env_file:
      - ../Search/.env
    networks:
      - search
    expose:
      - "27017"


volumes:
  search_db_data:
  search_requests_db_data:


networks:
  web:
    external: true
    name: shared-web
  rabbitmq:
    external: true
    name: shared-rabbitmq
  search:
    driver: bridge
