version: "3.9"

services:
  ngninx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d/:ro
      - ../Search/static/:/search/static/
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - users
      - search
      - payments
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq
    expose:
      - "5672"
      - "15672"


networks:
  web:
    driver: bridge
    name: shared-web
  rabbitmq:
    driver: bridge
    name: shared-rabbitmq
