version: "3.9"

services:
  search:
    build: ../Search
    env_file:
      - ../Search/.env
    networks:
      - search
      - web
    ports:
      - "3000:3000"
    volumes:
      - "../Search:/search"
    depends_on:
      search_db:
        condition: "service_started"
  search_db:
    image: postgres:12.0-alpine
    container_name: search_db
    volumes:
      - search_db_data:/var/lib/postgresql/data/
    env_file:
      - ../Search/.env
    networks:
      - search
    expose:
      - "5432"


volumes:
  search_db_data:


networks:
  web:
    external: true
    name: shared-web
  search:
    driver: bridge
