version: "3.9"

services:
  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d/:ro
      - ../Search/static/:/search/static/
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - users
      - search
      - payments
      - iot-logs
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq
    expose:
      - "5672"
      - "15672"
  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - redis
  centrifugo:
    image: centrifugo/centrifugo
    env_file:
      - ../centrifugo/.env
    volumes:
      - ../centrifugo/:/centrifugo/
    command: centrifugo -c config.json
    ports:
      - "8080:8000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - centrifugo
      - redis
    depends_on:
      - redis

networks:
  web:
    driver: bridge
    name: shared-web
  rabbitmq:
    driver: bridge
    name: shared-rabbitmq
  redis:
    driver: bridge
    name: shared-redis
  centrifugo:
    driver: bridge
    name: shared-centrifugo
