version: "3.9"

services:
  payments:
    build: ../Payments/
    container_name: payments
    env_file:
      - ../Payments/.env
    networks:
      - payments
      - web
      - kafka
      - rabbitmq
    expose:
      - "7000"
    volumes:
      - "../Payments:/app"
    depends_on:
      booking_db:
        condition: "service_started"
      rabbitmq:
        condition: "service_healthy"
  booking_db:
    image: postgres:12.0-alpine
    container_name: booking_db
    volumes:
      - booking_db_data:/var/lib/postgresql/data/
    env_file:
      - ../Payments/.env
    networks:
      - payments
    expose:
      - "5432"


volumes:
  booking_db_data:


networks:
  web:
    external: true
    name: shared-web
  rabbitmq:
    external: true
    name: shared-rabbitmq
  kafka:
    external: true
    name: shared-kafka
  payments:
    driver: bridge
