version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web
    ports:
      - "5672:5672"
      - "15672:15672"


networks:
  web:
    driver: bridge
    name: shared-web
