# Generated by Django 4.1.3 on 2022-11-20 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='succeeded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 13, 8, 29, 129760)),
            preserve_default=False,
        ),
    ]
