# Generated by Django 4.1.1 on 2022-10-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_key',
            field=models.ImageField(upload_to='', verbose_name='Image key'),
        ),
    ]
