# Generated by Django 4.1.1 on 2022-10-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_hotel_images'),
        ('rooms', '0007_remove_room_images'),
        ('images', '0002_alter_image_image_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.ImageField(upload_to='hotels', verbose_name='Image key')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Hotel image')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.ImageField(upload_to='rooms', verbose_name='Image key')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Room image')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
