# Generated by Django 4.1.1 on 2022-10-04 20:26

import images.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_hotel_images'),
        ('images', '0003_hotelimage_roomimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image_key',
            field=models.ImageField(upload_to=images.utils.path_and_rename, verbose_name='Image key'),
        ),
    ]
