# Generated by Django 4.1.1 on 2022-10-04 20:36

import images.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_hotelimage_hotel_alter_hotelimage_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image name'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image_key',
            field=models.ImageField(upload_to=functools.partial(images.utils.path_and_rename, *('hotels',), **{}), verbose_name='Image key'),
        ),
    ]
