# Generated by Django 4.1.1 on 2022-10-04 20:56

import images.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_hotelimage_image_name_alter_hotelimage_image_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image_key',
            field=models.ImageField(upload_to=images.utils.path_and_rename, verbose_name='Image key'),
        ),
    ]
