apiVersion: v1
kind: Service
metadata:
  labels:
    service: users
  name: users
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service: users
status:
  loadBalancer: {}
