name: Deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to GCP & Launch
        env:
          HOSTNAME: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PRIVATE_PEM_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          echo "${PRIVATE_PEM_KEY}" > backend_server_key.pem
          chmod 400 backend_server_key.pem
          rsync \
            --archive \
            --verbose \
            --compress \
            --delete-before \
            --exclude={"*.pem","*.env","*/__pycache__","*/static/*"} \
            --rsh="ssh -o StrictHostKeyChecking=no -i backend_server_key.pem" \
            `pwd` ${USERNAME}@${HOSTNAME}:/home/${USERNAME}/
          ssh -o StrictHostKeyChecking=no -i backend_server_key.pem ${USERNAME}@${HOSTNAME} "cd ${REPOSITORY_NAME}; make run"
